# config/_default/config.toml
baseURL = "http://dev.tratamentes.pt"
theme = "landing"
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = true
enableMultilingual = true
enableRobotsTXT = true
enableGitInfo = true
publishDir = "dist"


# Adicionar configuração dos módulos e shortcodes
[module]
  [[module.mounts]]
    source = "layouts/shortcodes"
    target = "layouts/shortcodes"
  [[module.mounts]]
    source = "themes/landing/layouts/shortcodes"
    target = "layouts/shortcodes"

# Depois o conteúdo para cada idioma
  [[module.mounts]]
    source = "content/pt"
    target = "content"
    lang = "pt"
  
  [[module.mounts]]
    source = "content/en"
    target = "content"
    lang = "en"
  
  [[module.mounts]]
    source = "content/es"
    target = "content"
    lang = "es"

  # Configurações adicionais necessárias
  [[module.mounts]]
    source = "static"
    target = "static"
  
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "assets/scss"
    target = "assets/scss"
  
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  
  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"


[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[server]
  logFile = "hugo-server.log"

[markup.goldmark.renderer]
  unsafe = true

[build]
  writeStats = true

[build.processing]
  [build.processing.css]
    includePaths = ["themes/landing/assets/scss"]
    method = "dart-sass"
    options = { targetPath = "css/styles.css", outputStyle = "compressed", enableSourceMap = true }

[[redirects]]
  from = '/**'
  status = 404
  to = '/404.html'