# Configuração base do site
baseURL = "https://tratamentes.pt"
title = "TrataMentes - Terapia Manual & Massagem | João Goulart"
theme = "landing"
defaultContentLanguage = "pt"
enableMultilingual = true
enableRobotsTXT = true
enableGitInfo = true

[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[permalinks]
  services = "/tratamentos/:slug/"

# Parâmetros globais
[params]
  description = "Massoterapeuta experiente com formação em osteopatia. Disponibilizo um tratamento holístico, combinando técnicas de massagem e conhecimentos em saúde. No meu espaço acolhedor, encontrará o ambiente perfeito para relaxar e cuidar de si. O seu bem-estar é a minha prioridade."
  author = "TrataMentes"
  logo = "/images/logo-tipo-tratamentes-horizontal-inv-verde-DFE9CE.svg"
  debug = true
  googleApiKey = "AIzaSyDaAyhHYJ0mctY9TKUTqzvpekC3G6Qjk2w"

  [params.colors]
    primary = "#4A90E2"
    secondary = "#2C5282"
    accent = "#48BB78"

  [params.fonts]
    heading = "Montserrat"
    body = "Inter"

  [params.contact]
    email = "joao.goulart@tratamentes.pt"
    phone = "+351 937 543 312"
    addresses = [
      "Rua Braamcamp 88, 3Esq, 1250-012 Lisboa",
      "Rua Jorge Colaço 32A, 1700-253 Lisboa"
    ]
    lat = "38.721462924719525"
    lng = "-9.152609455660295"

  [params.social]
    facebook = "https://www.facebook.com/trata.mentes/"
    instagram = "https://instagram.com/trata.mentes"
    linkedin = "https://linkedin.com/company/tratamentes"

  [params.analytics]
    googleAnalytics = false
    googleAnalyticsID = "G-XXXXXXXXXX"
    googleTagManager = false
    googleTagManagerID = "GTM-XXXXXX"
    microsoftClarity = false
    microsoftClarityID = "XXXXXXXX"
    facebookPixel = false
    facebookPixelID = "XXXXXXXXXX"

  [params.cookieConsent]
    enable = true
    type = "opt-in"
    position = "bottom"

  [params.seo]
    schema = true
    openGraph = true
    twitterCards = true

  [params.performance]
    [params.performance.images]
      lazy = true
      sizes = [480, 720, 1080, 1366, 1920]
      formats = ["webp", "jpg"]
      quality = 85

    [params.performance.assets]
      minifyCSS = true
      minifyJS = true
      bundleCSS = true
      bundleJS = true

    [params.performance.cache]
      enableBrowser = true
      maxAge = 31536000

    [params.performance.critical]
      enable = true
      includePaths = ["/", "/tratamentos/*"]

    [params.performance.preload]
      fonts = true
      criticalImages = true

    [params.performance.defer]
      nonCriticalCSS = true
      nonCriticalJS = true

    [params.performance.responsive]
      breakpoints = ["sm", "md", "lg", "xl", "2xl"]
      defaultBreakpoint = "lg"
      mobileFriendly = true
      touchOptimized = true

  [params.business]
    name = "TrataMentes"
    founder = "João Paulo Goulart"
    location = "Lisboa"
    country = "PT"
    email = "joao.goulart@tratamentes.pt"
    phone = "+351937543312"

# Configurações de idiomas
[languages]
  [languages.pt]
    languageName = "Português"
    contentDir = "content/pt"
    weight = 1
    title = "TrataMentes - Terapia Manual & Massagem | João Goulart"
    
    [languages.pt.params]
      lang = "pt"

    [[languages.pt.menu.main]]
      identifier = "tratamentos"
      name = "Tratamentos"
      url = "/tratamentos/"
      weight = 10

      [[languages.pt.menu.main]]
        parent = "tratamentos"
        name = "Massagem Terapêutica"
        url = "/tratamentos/massagem-terapeutica/"
        weight = 1

      [[languages.pt.menu.main]]
        parent = "tratamentos"
        name = "Massagem Relaxamento"
        url = "/tratamentos/massagem-relaxamento/"
        weight = 2

      [[languages.pt.menu.main]]
        parent = "tratamentos"
        name = "Osteopatia"
        url = "/tratamentos/osteopatia/"
        weight = 3

      [[languages.pt.menu.main]]
        parent = "tratamentos"
        name = "Ver Todos"
        url = "/tratamentos/"
        weight = 4

    [[languages.pt.menu.main]]
      name = "Início"
      url = "/"
      weight = 1

    [[languages.pt.menu.main]]
      name = "Sobre"
      url = "/sobre/"
      weight = 2

    [[languages.pt.menu.main]]
      name = "Contacto"
      url = "/contacto/"
      weight = 3

    [[languages.pt.menu.footer]]
      name = "Termos e Condições"
      url = "/termos-e-condicoes/"
      weight = 1

    [[languages.pt.menu.footer]]
      name = "Política de Privacidade"
      url = "/politica-de-privacidade/"
      weight = 2

    [[languages.pt.menu.footer]]
      name = "Política de Cookies"
      url = "/politica-de-cookies/"
      weight = 3

  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    title = "TrataMentes - Manual Therapy & Massage | João Goulart"
    
    [languages.en.params]
      lang = "en"

    [[languages.en.menu.main]]
      identifier = "treatments"
      name = "Treatments"
      url = "/treatments/"
      weight = 10

      [[languages.en.menu.main]]
        parent = "treatments"
        name = "Therapeutic Massage"
        url = "/treatments/therapeutic-massage/"
        weight = 1

      [[languages.en.menu.main]]
        parent = "treatments"
        name = "Relaxation Massage"
        url = "/treatments/relaxation-massage/"
        weight = 2

      [[languages.en.menu.main]]
        parent = "treatments"
        name = "Osteopathy"
        url = "/treatments/osteopathy/"
        weight = 3

      [[languages.en.menu.main]]
        parent = "treatments"
        name = "View All"
        url = "/treatments/"
        weight = 4

    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1

    [[languages.en.menu.main]]
      name = "About"
      url = "/about/"
      weight = 2

    [[languages.en.menu.main]]
      name = "Contact"
      url = "/contact/"
      weight = 3

    [[languages.en.menu.footer]]
      name = "Terms & Conditions"
      url = "/terms-and-conditions/"
      weight = 1

    [[languages.en.menu.footer]]
      name = "Privacy Policy"
      url = "/privacy-policy/"
      weight = 2

    [[languages.en.menu.footer]]
      name = "Cookie Policy"
      url = "/cookie-policy/"
      weight = 3

  [languages.es]
    languageName = "Español"
    contentDir = "content/es"
    weight = 3
    title = "TrataMentes - Terapia Manual & Masaje | João Goulart"
    
    [languages.es.params]
      lang = "es"

    [[languages.es.menu.main]]
      identifier = "tratamientos"
      name = "Tratamientos"
      url = "/tratamientos/"
      weight = 10

      [[languages.es.menu.main]]
        parent = "tratamientos"
        name = "Masaje Terapéutico"
        url = "/tratamientos/masaje-terapeutico/"
        weight = 1

      [[languages.es.menu.main]]
        parent = "tratamientos"
        name = "Masaje Relajante"
        url = "/tratamientos/masaje-relajante/"
        weight = 2

      [[languages.es.menu.main]]
        parent = "tratamientos"
        name = "Osteopatía"
        url = "/tratamientos/osteopatia/"
        weight = 3

      [[languages.es.menu.main]]
        parent = "tratamientos"
        name = "Ver Todos"
        url = "/tratamientos/"
        weight = 4

    [[languages.es.menu.main]]
      name = "Inicio"
      url = "/"
      weight = 1

    [[languages.es.menu.main]]
      name = "Sobre"
      url = "/sobre/"
      weight = 2

    [[languages.es.menu.main]]
      name = "Contacto"
      url = "/contacto/"
      weight = 3

    [[languages.es.menu.footer]]
      name = "Términos y Condiciones"
      url = "/terminos-y-condiciones/"
      weight = 1

    [[languages.es.menu.footer]]
      name = "Política de Privacidad"
      url = "/politica-de-privacidad/"
      weight = 2

    [[languages.es.menu.footer]]
      name = "Política de Cookies"
      url = "/politica-de-cookies/"
      weight = 3

[build]
  writeStats = true

[build.processing]
  css = true
  js = true

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true